#!/bin/bash
#
# gen-sailfish-patch 0.0.1 (2018-11-10)
# Copyright (C) 2016  Cornerman (https://github.com/cornerman/gen-sailfish-patch)
#               2018  Mirian Margiani
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

DEPENDENCIES=()

dependencies() { # 1: echo/no-echo
    ret=0
    print=
    if [[ "$1" == "echo" ]]; then
        print=true
        echo -e "\nDependencies:"
    fi

    for i in "${DEPENDENCIES[@]}"; do
        if which "$i" 2> /dev/null >&2; then
            if [[ -n "$print" ]]; then
                echo "    - $i: $(which "$i")"
            fi
        else
            if [[ -n "$print" ]]; then
                echo "    - $i: missing"
                ret=1
            else
                return 1
            fi
        fi
    done

    return "$ret"
}

version() {
    echo "\
gen-sailfish-patch 0.0.1 (2018-11-10)
Copyright (C) 2018  Mirian Margiani
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law."
    dependencies echo
}

if ! dependencies no-echo; then
    version
    echo -e "\nerror: missing dependencies" >/dev/stderr
    exit 255
fi

show_help() {
script="$(basename "$0")"
    echo "\
** gen-sailfish-patch **

Lorem Ipsum dolor sit amet ...

Usage:
    $script ...
    $script [-h] [-V]

Arguments:
    -V, --version - show version and license information
    -h, --help    - show this help and exit
"
}

while [[ $# > 0 ]]; do
    case "$1" in
        --help|-h) show_help; exit 0;;
        --version|-V) version; exit 0;;
        -*) echo "unknown option: $1";;
        *) shift; continue;;
    esac
    shift
done

template_dir="$(dirname "$(readlink -f "$0")")/templates"

if [[ ! -d "$template_dir" ]]; then
    echo "error: template directory not found!"
    exit 1
fi

json_file="$template_dir/patch.json"
gitignore_file="$template_dir/gitignore"
spec_file="$template_dir/patch.spec"

out_dir="build"
patch_dir="$out_dir/patch"
rpm_dir="$out_dir/rpm"
prefix_file="$out_dir/dir"


if [[ ! -d .git ]]; then
    echo "error: not in the root directory of a Git repository!"
    exit 2
fi

project="$(basename "$(pwd)")"

orig_branch="$(git branch --list | grep -E '^\s*original$')"

if [[ -z "$orig_branch" ]]; then
    echo "error: missing 'original' branch!"
    echo "Create this branch and commit the original QML files without changes."
    echo "The diff is created based on this branch."
    exit 1
fi

if [[ -f "$prefix_file" ]]; then
    prefix_dir="$(cat "$prefix_file" | head -n 1)"
else
    prefix_dir="/"
    echo "$prefix_dir" > "$prefix_file"
fi

if [[ ! -d "$out_dir" ]]; then
    mkdir -p "$out_dir"
fi

if [[ ! -f "$out_dir/.gitignore" ]]; then
    cp "$gitignore_file" "$out_dir/.gitignore"
fi

if [[ ! -d "$rpm_dir" ]]; then
    mkdir -p "$rpm_dir"
    sed "s/Name: NAME/Name: $project/g;" "$spec_file" > "$rpm_dir/$project.spec"
fi

if [[ ! -d "$patch_dir" ]]; then
    mkdir -p "$patch_dir"
    cp "$json_file" "$patch_dir/patch.json"
fi

git diff original --src-prefix="a$prefix_dir" --dst-prefix="b$prefix_dir" -- . ':(exclude)build/*' > "$patch_dir/unified_diff.patch"
