#!/bin/bash
#
# gen-sailfish-patch 0.0.1 (2018-11-10)
# Copyright (C) 2016  Cornerman (https://github.com/cornerman/gen-sailfish-patch)
#               2018  Mirian Margiani
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

DEPENDENCIES=()

dependencies() { # 1: echo/no-echo
    ret=0
    print=
    if [[ "$1" == "echo" ]]; then
        print=true
        echo -e "\nDependencies:"
    fi

    for i in "${DEPENDENCIES[@]}"; do
        if which "$i" 2> /dev/null >&2; then
            if [[ -n "$print" ]]; then
                echo "    - $i: $(which "$i")"
            fi
        else
            if [[ -n "$print" ]]; then
                echo "    - $i: missing"
                ret=1
            else
                return 1
            fi
        fi
    done

    return "$ret"
}

version() {
    echo "\
gen-sailfish-patch 0.0.1 (2018-11-10)
Copyright (C) 2018  Mirian Margiani
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law."
    dependencies echo
}

if ! dependencies no-echo; then
    version
    echo -e "\nerror: missing dependencies" >/dev/stderr
    exit 255
fi

show_help() {
script="$(basename "$0")"
    echo "\
** gen-sailfish-patch **

Lorem Ipsum dolor sit amet ...

Usage:
    $script ...
    $script [-h] [-V]

Arguments:
    -V, --version - show version and license information
    -h, --help    - show this help and exit
"
}

while [[ $# > 0 ]]; do
    case "$1" in
        --help|-h) show_help; exit 0;;
        --version|-V) version; exit 0;;
        -*) echo "unknown option: $1";;
        *) shift; continue;;
    esac
    shift
done

script_dir=$(dirname "$(readlink -f "$0")")
json_file="$script_dir/patch.json"
gitignore_file="$script_dir/gitignore"
spec_file="$script_dir/patch.spec"

out_dir="build"
patch_dir="$out_dir/patch"
rpm_dir="$out_dir/rpm"

orig_branch="$(git branch --list | grep -E '^\s*original$')"
if [ -z "$orig_branch" ]; then
    echo "Missing 'original' branch."
    echo "Create this branch and commit the original qml files without changes."
    echo "From there, the diff is created"
    exit 1
fi

[ -f dir ] && prefix_dir="$(cat dir | head -n 1)" || prefix_dir="/"

if [ ! -d "$out_dir" ]; then
    mkdir -p "$out_dir"
    cp "$gitignore_file" "$out_dir/.gitignore"
fi

if [ ! -d "$rpm_dir" ]; then
    mkdir -p "$rpm_dir"
    cp "$spec_file" "$rpm_dir/TODO.spec"
fi

if [ ! -d "$patch_dir" ]; then
    mkdir -p "$patch_dir"
    cp "$json_file" "$patch_dir/patch.json"
fi

git diff original --src-prefix="a$prefix_dir" --dst-prefix="b$prefix_dir" **/*.qml > $patch_dir/unified_diff.patch
